[scene]
buffer = true

# ground
[[pass]]
clear     = [0.38, 0.2, 0.7, 1.0]
draw      = {mode = "triangles", count = 2}
depth     = "less"
vertex    = "./ground.vert.glsl"
fragment  = "./ground.frag.glsl"
buffer    = "scene"

# quad
[[pass]]
blend     = {src = "src-alpha",  dst= "one-minus-src-alpha" }
draw      = {mode = "triangles", count = 2}
depth     = "less"
vertex    = "./quad.vert.glsl"
fragment  = "./pass.frag.glsl"
buffer    = "scene"

# ui
[[pass]]
draw      = {mode = "lines", count = 3}
vertex    = "./ui.vert.glsl"
fragment  = "./pass.frag.glsl"
buffer    = "scene"

# post-fx
[[pass]]
draw      = {mode = "triangles", count = 1}
vertex    = "../share/fullscreen_triangle.glsl"
fragment  = "./post.frag.glsl"
iChannel0 = "scene"