[webcam]
#windows
pipeline = "ksvideosrc ! videoconvert ! video/x-raw,format=BGRA ! appsink name=appsink async=false sync=false"
#macos
#pipeline = "autovideosrc ! video/x-raw,format=BGRA ! appsink name=appsink async=false sync=false"



[[pass]]
clear     = [0.0, 0.0, 0.0, 1.0]
draw      = {mode = "triangles", count = 1}
vertex    = "../share/fullscreen_triangle.glsl"
fragment  = "./image.glsl"
iChannel0 = "webcam"
