[video]
video = "https://upload.wikimedia.org/wikipedia/commons/3/3c/After_Storm_%284K_Resolution%29.webm"

[[pass]]
clear     = [0.0, 0.0, 0.0, 1.0]
draw      = {mode = "triangles", count = 1}
vertex    = "../share/fullscreen_triangle.glsl"
fragment  = "./image.glsl"
iChannel0 = "video"
